<?php

// autoload_real.php @generated by Composer

require_once(__DIR__ . '/BankConnector.php');
require_once(__DIR__ . '/Entity/Bill.php');
require_once(__DIR__ . '/Entity/Card.php');
require_once(__DIR__ . '/Entity/CardAuthorisation.php');
require_once(__DIR__ . '/Entity/Transaction.php');

